apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lowlevelorchestrations.charity-project.eu
spec:
  scope: Namespaced
  group: charity-project.eu
  names:
    kind: LowLevelOrchestration
    plural: lowlevelorchestrations
    singular: lowlevelorchestration
    shortNames:
    - llorch
  versions:
    - name: v1
      served: true
      storage: true
      schema: 
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusters:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      uid:
                        type: string
                      provider:
                        type: string
                      kubernetes-version:
                        type: string
                      control-plane-count:
                        type: integer
                        default: 1
                        minimum: 1
                      control-plane-flavor:
                        type: string
                      worker-machine-count:
                        type: integer
                        default: 0
                        minimum: 0
                      worker-machine-flavor:
                        type: string
                      image:
                        type: string
                links:
                  type: array
                  items:
                    type: array
                    minItems: 2
                    maxItems: 2
                    items:
                      type: string
                apps:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      cluster:
                        type: string
                      owner:
                        type: string
                      components:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            cluster-selector:
                              type: string
                            image:
                              type: string
                            expose:
                              type: array
                              items:
                                type: object
                                properties:
                                  is-public:
                                    type: boolean
                                  is-peered:
                                    type: boolean
                                  containerPort:
                                    type: integer
                                  clusterPort:
                                    type: integer
                            env:
                              type: object
                              properties:
                                is-secret:
                                  type: boolean
                                variables:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                      value:
                                        type: string
                            tls:
                              type: object
                              properties:
                                name:
                                  type: string
                                # certificate:
                                #   type: string
                                # key:
                                #   type: string
                            # registry:
                            #   type: object
                            #   properties:
                            #     repository:
                            #       type: string
                            #     username:
                            #       type: string
                            #     password:
                            #       type: string
                            #     email:
                            #       type: string

                  #x-kubernetes-validations:
                  #- rule: "self.all(x, size(self.filter(e, x.name == e.name)) == 1)"
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
