apiVersion: charity-project.eu/v1
kind: LowLevelOrchestration
metadata:
  name: kubeadm-based-orchestration
spec:
  clusters:
    - provider: "kubeadm"
      name: "blue"
      kubernetes-version: "v1.25.0"
      control-plane-count: 1
      control-plane-flavor: "m1.medium"
      worker-machine-count: 0
      worker-machine-flavor: "m1.medium"
      image: "ubuntu-2004-kube-v1.25"